# BOOK 도서 정보 , PRICE(판매가, 원)
# AUTHOR 저자 정보
# BOOK_SALES : 각 도서의 날짜 별 판매량 정보를 담은 테이블 , SALES(판매량)

# 2022년 1월의 도서 판매 데이터를 기준으로 저자 별, 카테고리 별 매출액(TOTAL_SALES = 판매량 * 판매가)을 구하여,
# AUTHOR_ID, AUTHOR_NAME, CATEGORY, SALES 리스트를 출력
# AUTHOR_ID ASC, CATGORY DESC

# 1. AUTHOR_NAME 을 합쳐주고
# 
SELECT 
    AUTHOR_ID,
    AUTHOR_NAME, 
    CATEGORY,
    SUM(PRICE*SALES) TOTAL_SALES
FROM 
BOOK_SALES S LEFT JOIN
(BOOK B LEFT JOIN AUTHOR A USING (AUTHOR_ID)) USING (BOOK_ID)
WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-01'
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC

