-- 코드를 입력하세요
# key : PRODUCT_ID
# 상품코드 별 매출액(판매가 * 판매량) 합계를 출력하는 SQL 문 작성
# 매출액 기준 내림차순 정렬, 매출액이 같다면 상품코드를 기준으로 오름차순
# PRICE : 판매가, SALES_AMOUNT : 판매량

SELECT SUB.PRODUCT_CODE, SUM(SUB.SALES) SALES
FROM
(SELECT P.PRODUCT_ID, P.PRODUCT_CODE, P.PRICE*S.SALES_AMOUNT SALES
FROM PRODUCT P INNER JOIN OFFLINE_SALE S ON P.PRODUCT_ID=S.PRODUCT_ID) SUB
GROUP BY SUB.PRODUCT_CODE
ORDER BY 
    SALES DESC, 
    PRODUCT_CODE