-- 코드를 입력하세요
# 입양을 간 동물 중, 보호 기간이 가장 길었던 동물 두 마리의 아이디와 이름을 조회

# SELECT 
#     I.ANIMAL_ID,
#     I.NAME,
#     DATEDIFF(O.DATETIME - I.DATETIME) DIFF_DATE
# FROM ANIMAL_INS I LEFT JOIN ANIMAL_OUTS O USING (ANIMAL_ID)
                                                 
SELECT I.ANIMAL_ID, I.NAME
FROM ANIMAL_INS I JOIN ANIMAL_OUTS O USING (ANIMAL_ID)
ORDER BY TIMESTAMPDIFF(DAY, I.DATETIME, O.DATETIME) DESC
LIMIT 2;