-- 코드를 입력하세요
# 게시물 3건 이상 등록 
# USER_ID, NICKNAME, 전체주소, 전화본호 조회 
# 시, 도로명 주소, 상세 주소 함께 출력 
# 전화번호 - 추가

SELECT USER_ID, NICKNAME, 전체주소, 전화번호
FROM
(SELECT 
    WRITER_ID AS USER_ID,
    NICKNAME,
    CONCAT(CITY, ' ', STREET_ADDRESS1, ' ', STREET_ADDRESS2) AS 전체주소,
    CONCAT(SUBSTR(TLNO, 1, 3), '-', SUBSTR(TLNO, 4, 4), '-', SUBSTR(TLNO, 8, 4)) AS 전화번호,
    COUNT(*) AS USER_COUNT
FROM USED_GOODS_BOARD B LEFT JOIN USED_GOODS_USER U ON B.WRITER_ID = U.USER_ID
GROUP BY WRITER_ID) SUB
WHERE USER_COUNT > 2
ORDER BY USER_ID DESC 
