# REST_ID : KEY

# SELECT *
# FROM REST_INFO

# SELECT * 
# FROM REST_REVIEW

# 서울에 위치한 식당 
# 식당 ID, 식당 이름, 음식 종류, 즐겨찾기수, 주소, 리뷰 평균 점수
# 리뷰 평균 점수 : 소수점 세 번째 자리에서 반올림 
# 평균점수를 기준으로 내림차순 정렬 -> 즐겨찾기수 내림차순

# SELECT 
#     REST_ID,
#     REST_NAME, 
#     FOOD_TYPE, 
#     FAVORITES,
#     ADDRESS,
#     ROUND(AVG(REVIEW_SCORE), 2) SCORE
# FROM REST_REVIEW R JOIN REST_INFO I USING (REST_ID)
# WHERE ADDRESS LIKE "%서울%"
# GROUP BY REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS
# ORDER BY SCORE DESC, FAVORITES DESC 

SELECT i.REST_ID, i.REST_NAME, i.FOOD_TYPE, i.FAVORITES, i.ADDRESS, ROUND(AVG(r.REVIEW_SCORE), 2) AS "SCORE"
FROM REST_INFO i
INNER JOIN REST_REVIEW r
ON i.REST_ID = r.REST_ID 
WHERE i.ADDRESS LIKE '서울%'
GROUP BY REST_ID
ORDER BY 6 DESC, 4 DESC;
