# 자동차 정보 : CAR_RENTAL_COMPANY_CAR 

# 자동차 종류가 '트럭' 인 자동차 
# 대여 기록 별로 대여 금액을 구하여 대여 기록 ID 와 대여 금액 리스트를 출력
# 대여 금액 내림차순, 대여 기록 ID 내림차순

# 기간별로 JOIN 을 시켜줘야 한다.
# CTE (COMMON TABLE EXPRESSIONS) 임시 테이블
WITH SUB AS (
SELECT 
    C.DAILY_FEE,
    C.CAR_TYPE,
    H.HISTORY_ID, 
    DATEDIFF(H.END_DATE, H.START_DATE) + 1 AS DURATION,
    CASE WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 90 THEN '90일 이상'
         WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 30 THEN '30일 이상'
         WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 7 THEN '7일 이상'
         ELSE 'NONE' END AS DURATION_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H 
JOIN CAR_RENTAL_COMPANY_CAR AS C 
ON C.CAR_ID = H.CAR_ID
WHERE C.CAR_TYPE = '트럭')

SELECT 
    SUB.HISTORY_ID, 
    ROUND(SUB.DAILY_FEE * (100 - IFNULL(P.DISCOUNT_RATE, 0)) / 100) * SUB.DURATION AS FEE
FROM SUB
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P
ON SUB.CAR_TYPE = P.CAR_TYPE 
AND SUB.DURATION_TYPE = P.DURATION_TYPE -- 두 개의 JOIN KEY 가 필요
ORDER BY FEE DESC, HISTORY_ID DESC