-- 코드를 입력하세요
# 중고 거래 게시판 정보 USED_GOODS_BOARD
# 중고 거래 게시판 사용자 정보 USED_GOODS_USER
SELECT 
    B.WRITER_ID USER_ID,
    U.NICKNAME NICKNAME,
    SUM(PRICE) TOTAL_SALES
FROM USED_GOODS_BOARD B LEFT JOIN USED_GOODS_USER U ON B.WRITER_ID = U.USER_ID
WHERE B.STATUS = 'DONE'
GROUP BY USER_ID
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES