# 1. MEMBER_ID를 통해 두 테이블을 조인한다. 
# 2. 가장 많은 리뷰를 작성한 회원을 찾아야 하므로 WHERE 조건절에서 GROUP BY 로 묶고 LIMIT 1을 주어 가장 위에 있는 값을 가져온다.


SELECT 
    A.MEMBER_NAME,
    B.REVIEW_TEXT,
    DATE_FORMAT(B.REVIEW_DATE, "%Y-%m-%d") AS REVIEW_DATE
FROM MEMBER_PROFILE A join REST_REVIEW B USING (MEMBER_ID)
WHERE A.MEMBER_ID = (SELECT MEMBER_ID FROM REST_REVIEW
GROUP BY MEMBER_ID
ORDER BY COUNT(*) DESC LIMIT 1)
ORDER BY REVIEW_DATE, REVIEW_TEXT