SELECT MONTH(START_DATE) MONTH, CAR_ID, COUNT(*) RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE (MONTH(START_DATE) BETWEEN 8 AND 10) AND (CAR_ID IN
(SELECT CAR_ID
 FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
 WHERE MONTH(START_DATE) BETWEEN 8 AND 10
GROUP BY CAR_ID
HAVING COUNT(*) >= 5)) # 조건 1 : 8월과 10월 조건 2: 총 대여 횟수가 5회 이상
GROUP BY MONTH(START_DATE), CAR_ID  # 월별 자동차 ID별 
ORDER BY MONTH, CAR_ID DESC

# SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(*) AS RECORDS
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# WHERE (MONTH(START_DATE) BETWEEN 8 AND 10)
#   AND (CAR_ID IN (
#       SELECT CAR_ID
#       FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
#       WHERE MONTH(START_DATE) BETWEEN 8 AND 10
#       GROUP BY CAR_ID
#       HAVING COUNT(*) >= 5
#   ))
# GROUP BY MONTH(START_DATE), CAR_ID
# ORDER BY MONTH ASC, CAR_ID DESC;








