-- 코드를 입력하세요
# FIRST_HALF : 상반기 주문 정보
# ICECREAM_INFO : 아이스크림 성분 정보
# 성분 타입과 성분 타입에 대한 아이스크림의 총주문량을 총주문량이 작은 순서대로
SELECT INGREDIENT_TYPE, SUM(TOTAL_ORDER) TOTAL_ORDER
FROM FIRST_HALF F LEFT JOIN ICECREAM_INFO USING (FLAVOR)
GROUP BY INGREDIENT_TYPE