SELECT A.TITLE, A.BOARD_ID, B.REPLY_ID, B.WRITER_ID, B.CONTENTS, DATE_FORMAT(B.CREATED_DATE, '%Y-%m-%d') CREATED_DATE
FROM USED_GOODS_BOARD A INNER JOIN USED_GOODS_REPLY B USING(BOARD_ID)
WHERE SUBSTR(A.CREATED_DATE,1,7) = '2022-10'
ORDER BY CREATED_DATE, A.TITLE